# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 551ec4036cced223ed2f2f5173b481bd05d4fbf06bdbdda34fe892c990762c0ec0634fd341b49cd0f7bcfb33ce0f2b71ca5098bda37e2420ceda94866d7185ba

test:
  secret_key_base: 3cf03d04918d0ff39c2804e357b063b8e089dc9998451ba7022264d5c9af455fb41f426a79881abd578900ff3b189a43b2eb987a72e86138f574beb0d463d498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
